# Data Preparation

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import csv
import numpy as np

In [2]:
df = pd.read_csv("data/association.csv")
df.head()

Family  Hobbies  Social_Club  Political  Professional  Religious  \
0       1        0            0          0             0          0   
1       0        0            0          0             0          1   
2       1        1            0          0             1          0   
3       0        0            0          0             0          0   
4       0        0            0          1             1          0   

   Support_Group  
0              0  
1              1  
2              0  
3              0  
4              1

The data is in tabular format with zeros and ones. The data needs to be transformed.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3483 entries, 0 to 3482
Data columns (total 7 columns):
Family           3483 non-null int64
Hobbies          3483 non-null int64
Social_Club      3483 non-null int64
Political        3483 non-null int64
Professional     3483 non-null int64
Religious        3483 non-null int64
Support_Group    3483 non-null int64
dtypes: int64(7)
memory usage: 190.5 KB


In [4]:
for row in df.values:
    print row

[1 0 0 0 0 0 0]
[0 0 0 0 0 1 1]
[1 1 0 0 1 0 0]
[0 0 0 0 0 0 0]
[0 0 0 1 1 0 1]
[0 0 0 0 1 0 0]
[0 0 0 0 0 0 1]
[1 1 1 0 0 1 0]
[1 1 0 0 1 1 0]
[0 0 0 0 0 1 1]
[1 1 0 0 1 0 0]
[1 0 1 0 0 1 0]
[1 0 0 0 0 0 0]
[0 0 0 0 1 0 0]
[1 1 1 0 0 1 0]
[0 0 0 0 0 0 0]
[1 0 0 0 1 1 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 1 0]
[1 0 0 0 0 0 1]
[1 1 0 0 0 0 1]
[0 1 0 0 1 1 0]
[0 1 0 0 1 1 0]
[1 0 1 0 1 0 0]
[1 1 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 1]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[1 0 1 0 0 1 0]
[1 0 0 0 1 0 0]
[0 1 0 0 0 1 1]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 1 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 0 0]
[1 0 1 0 1 1 0]
[0 1 0 0 0 1 0]
[1 0 0 0 1 1 0]
[1 0 1 0 0 0 1]
[1 1 0 1 1 1 0]
[1 1 1 0 0 1 0]
[1 0 0 0 1 0 0]
[1 1 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 0 0 0]
[0 1 1 0 0 1 0]
[0 0 0 0 1 0 0]
[1 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 1 1 0 0 1 1]
[0 0 0 0 0 0 0]
[0 0 0 0 0 1 0]
[1 1 1 0 0 1 0]
[0 0 0 0 0 0 0]
[1 1 1 0 0 1 0]
[0 1 0 0 0 1 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[1 1 0 0

In [5]:
for row in df.values:
    print df.columns[row.astype(bool)].tolist()

['Family']
['Religious', 'Support_Group']
['Family', 'Hobbies', 'Professional']
[]
['Political', 'Professional', 'Support_Group']
['Professional']
['Support_Group']
['Family', 'Hobbies', 'Social_Club', 'Religious']
['Family', 'Hobbies', 'Professional', 'Religious']
['Religious', 'Support_Group']
['Family', 'Hobbies', 'Professional']
['Family', 'Social_Club', 'Religious']
['Family']
['Professional']
['Family', 'Hobbies', 'Social_Club', 'Religious']
[]
['Family', 'Professional', 'Religious']
[]
['Religious']
['Family', 'Support_Group']
['Family', 'Hobbies', 'Support_Group']
['Hobbies', 'Professional', 'Religious']
['Hobbies', 'Professional', 'Religious']
['Family', 'Social_Club', 'Professional']
['Family', 'Hobbies']
['Professional']
['Professional', 'Support_Group']
[]
[]
['Family', 'Social_Club', 'Religious']
['Family', 'Professional']
['Hobbies', 'Religious', 'Support_Group']
['Religious']
['Religious']
['Hobbies', 'Religious']
['Religious']
[]
['Family', 'Social_Club', 'Professional'

In [6]:
# convert the data and save using a variable

data = [df.columns[row.astype(bool)].tolist() for row in df.values]
data

[['Family'],
 ['Religious', 'Support_Group'],
 ['Family', 'Hobbies', 'Professional'],
 [],
 ['Political', 'Professional', 'Support_Group'],
 ['Professional'],
 ['Support_Group'],
 ['Family', 'Hobbies', 'Social_Club', 'Religious'],
 ['Family', 'Hobbies', 'Professional', 'Religious'],
 ['Religious', 'Support_Group'],
 ['Family', 'Hobbies', 'Professional'],
 ['Family', 'Social_Club', 'Religious'],
 ['Family'],
 ['Professional'],
 ['Family', 'Hobbies', 'Social_Club', 'Religious'],
 [],
 ['Family', 'Professional', 'Religious'],
 [],
 ['Religious'],
 ['Family', 'Support_Group'],
 ['Family', 'Hobbies', 'Support_Group'],
 ['Hobbies', 'Professional', 'Religious'],
 ['Hobbies', 'Professional', 'Religious'],
 ['Family', 'Social_Club', 'Professional'],
 ['Family', 'Hobbies'],
 ['Professional'],
 ['Professional', 'Support_Group'],
 [],
 [],
 ['Family', 'Social_Club', 'Religious'],
 ['Family', 'Professional'],
 ['Hobbies', 'Religious', 'Support_Group'],
 ['Religious'],
 ['Religious'],
 ['Hobbies', '

# Network Visualization

We will use **networkx**, ptyhon package for network analysis.

Before installing, let's check if the package is already in your machine by typing in **conda list networkx**
- If the packge is not found, then **pip install networkx**
- If the package is found, then **pip install --upgrade networkx**

### First, transform data into edgelists

In [7]:
for i in data:
    print i

['Family']
['Religious', 'Support_Group']
['Family', 'Hobbies', 'Professional']
[]
['Political', 'Professional', 'Support_Group']
['Professional']
['Support_Group']
['Family', 'Hobbies', 'Social_Club', 'Religious']
['Family', 'Hobbies', 'Professional', 'Religious']
['Religious', 'Support_Group']
['Family', 'Hobbies', 'Professional']
['Family', 'Social_Club', 'Religious']
['Family']
['Professional']
['Family', 'Hobbies', 'Social_Club', 'Religious']
[]
['Family', 'Professional', 'Religious']
[]
['Religious']
['Family', 'Support_Group']
['Family', 'Hobbies', 'Support_Group']
['Hobbies', 'Professional', 'Religious']
['Hobbies', 'Professional', 'Religious']
['Family', 'Social_Club', 'Professional']
['Family', 'Hobbies']
['Professional']
['Professional', 'Support_Group']
[]
[]
['Family', 'Social_Club', 'Religious']
['Family', 'Professional']
['Hobbies', 'Religious', 'Support_Group']
['Religious']
['Religious']
['Hobbies', 'Religious']
['Religious']
[]
['Family', 'Social_Club', 'Professional'

In [8]:
# generating network data

from itertools import combinations

nodes = [x for d in data for x in combinations(d, 2)]
nodes

[('Religious', 'Support_Group'),
 ('Family', 'Hobbies'),
 ('Family', 'Professional'),
 ('Hobbies', 'Professional'),
 ('Political', 'Professional'),
 ('Political', 'Support_Group'),
 ('Professional', 'Support_Group'),
 ('Family', 'Hobbies'),
 ('Family', 'Social_Club'),
 ('Family', 'Religious'),
 ('Hobbies', 'Social_Club'),
 ('Hobbies', 'Religious'),
 ('Social_Club', 'Religious'),
 ('Family', 'Hobbies'),
 ('Family', 'Professional'),
 ('Family', 'Religious'),
 ('Hobbies', 'Professional'),
 ('Hobbies', 'Religious'),
 ('Professional', 'Religious'),
 ('Religious', 'Support_Group'),
 ('Family', 'Hobbies'),
 ('Family', 'Professional'),
 ('Hobbies', 'Professional'),
 ('Family', 'Social_Club'),
 ('Family', 'Religious'),
 ('Social_Club', 'Religious'),
 ('Family', 'Hobbies'),
 ('Family', 'Social_Club'),
 ('Family', 'Religious'),
 ('Hobbies', 'Social_Club'),
 ('Hobbies', 'Religious'),
 ('Social_Club', 'Religious'),
 ('Family', 'Professional'),
 ('Family', 'Religious'),
 ('Professional', 'Religious'

In [9]:
# You could generate a csv file and do network visualization using Gephi

df = pd.DataFrame(nodes)
df.to_csv("data/networkvisualization_2.csv", index=False, header=None)

### Gephic 
Gephi is an advanced data visualization software (free, opensource).
You can download Gephi from https://gephi.org/users/download/

<img src = "images\network_2.png">